# Generated by Django 5.1.2 on 2024-11-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
