# Generated by Django 5.1.2 on 2024-11-02 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='article.review'),
        ),
    ]
