# Generated by Django 5.1.2 on 2024-11-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_review_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='articles/%Y/%m/%d'),
        ),
    ]
